#define bg #1E1E2E
#define fg #CDD6F4
#define cc #94e2d5

! black
#define c00 #45475A
#define c08 #585B70

! red
#define c01 #F38BA8
#define c09 #F38BA8

! green
#define c02 #A6E3A1
#define c10 #A6E3A1

! yellow
#define c03 #F9E2AF
#define c11 #F9E2AF

! blue
#define c04 #89B4FA
#define c12 #89B4FA

! magenta
#define c05 #F5C2E7
#define c13 #F5C2E7

! cyan
#define c06 #94E2D5
#define c14 #94E2D5

! white
#define c07 #BAC2DE
#define c15 #A6ADC8

#define black #000000
#define accent #77216f



