#define bg #272822
#define fg #f1ebeb
#define cc #66efd5

! black
#define c00 #48483e
#define c08 #76715e

! red
#define c01 #dc2566
#define c09 #fa2772

! green
#define c02 #8fc029
#define c10 #a7e22e

! yellow
#define c03 #d4c96e
#define c11 #e7db75 

! blue
#define c04 #55bcce
#define c12 #66d9ee

! magenta
#define c05 #9358fe
#define c13 #ae82ff

! cyan
#define c06 #56b7a5
#define c14 #66efd5

! white
#define c07 #acada1
#define c15 #cfd0c2

#define black #000000
#define accent #e92020



